name: UI Sentry Release

on:
  push:
    branches: [main]
    paths:
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sentry Release
        uses: getsentry/action-release@v1.1.5
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ey-demo-org
          SENTRY_PROJECT: demo-frontend
        with:
          version: 3.1.0
          environment: production
          set_commits: auto
          finalize: true
          sourcemaps: ./build
